version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: boycott_postgres
    restart: always
    environment:
      POSTGRES_USER: boycott_user
      POSTGRES_PASSWORD: boycott_password
      POSTGRES_DB: boycott_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

