export const badges = [
  {
    code: 'first_scan',
    nameEn: 'First Scan',
    nameAr: 'الماسح الأول',
    descriptionEn: 'Complete your first product scan',
    descriptionAr: 'أكمل أول عملية مسح للمنتج',
    icon: '🔍',
    requirement: JSON.stringify({ type: 'scans', count: 1 }),
  },
  {
    code: 'informed_shopper',
    nameEn: 'Informed Shopper',
    nameAr: 'المتسوق الواعي',
    descriptionEn: 'Scan 50 products',
    descriptionAr: 'امسح 50 منتجًا',
    icon: '🛒',
    requirement: JSON.stringify({ type: 'scans', count: 50 }),
  },
  {
    code: 'scan_master',
    nameEn: 'Scan Master',
    nameAr: 'خبير المسح',
    descriptionEn: 'Scan 200 products',
    descriptionAr: 'امسح 200 منتج',
    icon: '📱',
    requirement: JSON.stringify({ type: 'scans', count: 200 }),
  },
  {
    code: 'evidence_hunter',
    nameEn: 'Evidence Hunter',
    nameAr: 'صياد الأدلة',
    descriptionEn: 'Submit 5 approved evidences',
    descriptionAr: 'قدم 5 أدلة معتمدة',
    icon: '🔎',
    requirement: JSON.stringify({ type: 'approved_submissions', count: 5 }),
  },
  {
    code: 'local_guide',
    nameEn: 'Local Guide',
    nameAr: 'مرشد محلي',
    descriptionEn: 'Confirm 20 store availabilities',
    descriptionAr: 'أكد توفر 20 متجر',
    icon: '📍',
    requirement: JSON.stringify({ type: 'confirmations', count: 20 }),
  },
  {
    code: 'price_tracker',
    nameEn: 'Price Tracker',
    nameAr: 'متتبع الأسعار',
    descriptionEn: 'Update prices at 10 stores',
    descriptionAr: 'حدث الأسعار في 10 متاجر',
    icon: '💰',
    requirement: JSON.stringify({ type: 'price_updates', count: 10 }),
  },
  {
    code: 'streak_week',
    nameEn: 'Weekly Warrior',
    nameAr: 'محارب الأسبوع',
    descriptionEn: 'Maintain a 7-day scan streak',
    descriptionAr: 'حافظ على سلسلة مسح لمدة 7 أيام',
    icon: '🔥',
    requirement: JSON.stringify({ type: 'streak', days: 7 }),
  },
  {
    code: 'streak_month',
    nameEn: 'Streak Master',
    nameAr: 'ملك الاستمرارية',
    descriptionEn: 'Maintain a 30-day scan streak',
    descriptionAr: 'حافظ على سلسلة مسح لمدة 30 يومًا',
    icon: '⚡',
    requirement: JSON.stringify({ type: 'streak', days: 30 }),
  },
  {
    code: 'unmasker',
    nameEn: 'Unmasker',
    nameAr: 'كاشف الأقنعة',
    descriptionEn: 'View ownership chain for 25 brands',
    descriptionAr: 'اعرض سلسلة الملكية لـ 25 علامة تجارية',
    icon: '🎭',
    requirement: JSON.stringify({ type: 'unmasks', count: 25 }),
  },
  {
    code: 'community_pillar',
    nameEn: 'Community Pillar',
    nameAr: 'ركيزة المجتمع',
    descriptionEn: 'Reach Trusted Contributor status',
    descriptionAr: 'الوصول إلى حالة المساهم الموثوق',
    icon: '🏛️',
    requirement: JSON.stringify({ type: 'reputation_level', level: 2 }),
  },
  {
    code: 'first_submission',
    nameEn: 'First Contribution',
    nameAr: 'المساهمة الأولى',
    descriptionEn: 'Submit your first suggestion',
    descriptionAr: 'قدم اقتراحك الأول',
    icon: '✍️',
    requirement: JSON.stringify({ type: 'submissions', count: 1 }),
  },
  {
    code: 'helper',
    nameEn: 'Helpful Voter',
    nameAr: 'الناخب المفيد',
    descriptionEn: 'Vote on 20 community submissions',
    descriptionAr: 'صوت على 20 مساهمة مجتمعية',
    icon: '👍',
    requirement: JSON.stringify({ type: 'votes', count: 20 }),
  },
];

