export const companies = [
  // Parent companies to boycott
  {
    nameEn: 'The Coca-Cola Company',
    nameAr: 'شركة كوكا كولا',
    aliases: ['Coca Cola', 'Coke', 'كوكاكولا'],
    country: 'USA',
    description: 'Multinational beverage corporation',
    descriptionAr: 'شركة مشروبات متعددة الجنسيات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'PepsiCo',
    nameAr: 'بيبسيكو',
    aliases: ['Pepsi', 'بيبسي'],
    country: 'USA',
    description: 'Multinational food, snack, and beverage corporation',
    descriptionAr: 'شركة متعددة الجنسيات للأغذية والوجبات الخفيفة والمشروبات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Nestlé',
    nameAr: 'نستله',
    aliases: ['Nestle', 'نستلة'],
    country: 'Switzerland',
    description: 'Multinational food and drink processing conglomerate',
    descriptionAr: 'تكتل متعدد الجنسيات لتصنيع الأغذية والمشروبات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Procter & Gamble',
    nameAr: 'بروكتر آند غامبل',
    aliases: ['P&G', 'بي آند جي'],
    country: 'USA',
    description: 'Multinational consumer goods corporation',
    descriptionAr: 'شركة متعددة الجنسيات للسلع الاستهلاكية',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Unilever',
    nameAr: 'يونيليفر',
    aliases: ['يونيليفير'],
    country: 'UK/Netherlands',
    description: 'Multinational consumer goods company',
    descriptionAr: 'شركة متعددة الجنسيات للسلع الاستهلاكية',
    verdictLabel: 'CAUTION' as const,
    status: 'VERIFIED' as const,
    confidence: 'MEDIUM' as const,
  },
  {
    nameEn: "McDonald's Corporation",
    nameAr: 'شركة ماكدونالدز',
    aliases: ['McDonalds', 'ماكدونالدز', 'ماك'],
    country: 'USA',
    description: 'Multinational fast food corporation',
    descriptionAr: 'شركة متعددة الجنسيات للوجبات السريعة',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Starbucks Corporation',
    nameAr: 'شركة ستاربكس',
    aliases: ['Starbucks', 'ستاربكس'],
    country: 'USA',
    description: 'Multinational chain of coffeehouses',
    descriptionAr: 'سلسلة متعددة الجنسيات من المقاهي',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'HP Inc.',
    nameAr: 'شركة إتش بي',
    aliases: ['HP', 'Hewlett-Packard', 'اتش بي'],
    country: 'USA',
    description: 'Multinational technology company',
    descriptionAr: 'شركة تكنولوجيا متعددة الجنسيات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Puma SE',
    nameAr: 'بوما',
    aliases: ['Puma', 'بيوما'],
    country: 'Germany',
    description: 'Multinational sportswear company',
    descriptionAr: 'شركة ملابس رياضية متعددة الجنسيات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Mondelez International',
    nameAr: 'مونديليز إنترناشيونال',
    aliases: ['Mondelez', 'مونديليز'],
    country: 'USA',
    description: 'Multinational confectionery, food, and beverage company',
    descriptionAr: 'شركة متعددة الجنسيات للحلويات والأغذية والمشروبات',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: "L'Oréal",
    nameAr: 'لوريال',
    aliases: ['Loreal', 'L\'Oreal'],
    country: 'France',
    description: 'Multinational cosmetics and personal care company',
    descriptionAr: 'شركة متعددة الجنسيات لمستحضرات التجميل والعناية الشخصية',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Johnson & Johnson',
    nameAr: 'جونسون آند جونسون',
    aliases: ['J&J', 'جونسون'],
    country: 'USA',
    description: 'Multinational pharmaceutical and consumer goods company',
    descriptionAr: 'شركة متعددة الجنسيات للأدوية والسلع الاستهلاكية',
    verdictLabel: 'AVOID' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  // Alternative companies (PREFERRED)
  {
    nameEn: 'RC Cola International',
    nameAr: 'آر سي كولا',
    aliases: ['RC Cola', 'Royal Crown'],
    country: 'USA',
    description: 'Beverage company - alternative to major boycotted brands',
    descriptionAr: 'شركة مشروبات - بديل للعلامات التجارية المقاطعة',
    verdictLabel: 'PREFERRED' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Local Libyan Beverages',
    nameAr: 'مشروبات ليبية محلية',
    aliases: [],
    country: 'Libya',
    description: 'Local Libyan beverage producers',
    descriptionAr: 'منتجي المشروبات الليبيين المحليين',
    verdictLabel: 'PREFERRED' as const,
    status: 'VERIFIED' as const,
    confidence: 'HIGH' as const,
  },
  {
    nameEn: 'Turkish Brands',
    nameAr: 'علامات تجارية تركية',
    aliases: [],
    country: 'Turkey',
    description: 'Turkish consumer goods companies',
    descriptionAr: 'شركات السلع الاستهلاكية التركية',
    verdictLabel: 'PREFERRED' as const,
    status: 'VERIFIED' as const,
    confidence: 'MEDIUM' as const,
  },
];

