export const products = [
  // Coca-Cola products
  { 
    nameEn: 'Coca-Cola Classic 330ml', 
    nameAr: 'كوكا كولا كلاسيك 330مل', 
    brandName: 'Coca-Cola', 
    categoryName: 'Soft Drinks',
    barcode: '5449000000996',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Coca-Cola Zero 330ml', 
    nameAr: 'كوكا كولا زيرو 330مل', 
    brandName: 'Coca-Cola', 
    categoryName: 'Soft Drinks',
    barcode: '5449000131805',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Fanta Orange 330ml', 
    nameAr: 'فانتا برتقال 330مل', 
    brandName: 'Fanta', 
    categoryName: 'Soft Drinks',
    barcode: '5449000011527',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Sprite 330ml', 
    nameAr: 'سبرايت 330مل', 
    brandName: 'Sprite', 
    categoryName: 'Soft Drinks',
    barcode: '5449000014535',
    verdictLabel: 'AVOID' as const,
  },

  // Pepsi products
  { 
    nameEn: 'Pepsi Cola 330ml', 
    nameAr: 'بيبسي كولا 330مل', 
    brandName: 'Pepsi', 
    categoryName: 'Soft Drinks',
    barcode: '012000001536',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: '7UP 330ml', 
    nameAr: 'سفن أب 330مل', 
    brandName: '7UP', 
    categoryName: 'Soft Drinks',
    barcode: '012000100079',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Mountain Dew 330ml', 
    nameAr: 'ماونتن ديو 330مل', 
    brandName: 'Mountain Dew', 
    categoryName: 'Soft Drinks',
    barcode: '012000100048',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: "Lay's Classic Chips 170g", 
    nameAr: "ليز كلاسيك شيبس 170غ", 
    brandName: "Lay's", 
    categoryName: 'Snacks & Sweets',
    barcode: '028400064057',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Doritos Nacho Cheese 170g', 
    nameAr: 'دوريتوس ناتشو تشيز 170غ', 
    brandName: 'Doritos', 
    categoryName: 'Snacks & Sweets',
    barcode: '028400028721',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Cheetos Crunchy 227g', 
    nameAr: 'شيتوس كرنشي 227غ', 
    brandName: 'Cheetos', 
    categoryName: 'Snacks & Sweets',
    barcode: '028400039734',
    verdictLabel: 'AVOID' as const,
  },

  // Nestlé products
  { 
    nameEn: 'Nescafé Classic 200g', 
    nameAr: 'نسكافيه كلاسيك 200غ', 
    brandName: 'Nescafé', 
    categoryName: 'Coffee & Tea',
    barcode: '7613036932875',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'KitKat 4 Finger', 
    nameAr: 'كيت كات 4 أصابع', 
    brandName: 'KitKat', 
    categoryName: 'Snacks & Sweets',
    barcode: '5000112628265',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Maggi Chicken Cubes', 
    nameAr: 'ماجي مكعبات دجاج', 
    brandName: 'Maggi', 
    categoryName: 'Food',
    barcode: '7613034656889',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Nido Milk Powder 900g', 
    nameAr: 'نيدو حليب بودرة 900غ', 
    brandName: 'Nido', 
    categoryName: 'Dairy',
    barcode: '7613033464058',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Cerelac Wheat 400g', 
    nameAr: 'سيريلاك قمح 400غ', 
    brandName: 'Cerelac', 
    categoryName: 'Baby Food',
    barcode: '7613033434662',
    verdictLabel: 'AVOID' as const,
    description: 'Baby food - consider alternatives carefully',
    descriptionAr: 'طعام أطفال - ابحث عن بدائل بعناية',
  },

  // P&G products
  { 
    nameEn: 'Tide Detergent 3kg', 
    nameAr: 'تايد مسحوق غسيل 3كغ', 
    brandName: 'Tide', 
    categoryName: 'Household Cleaning',
    barcode: '037000389583',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Ariel Detergent 3kg', 
    nameAr: 'أريال مسحوق غسيل 3كغ', 
    brandName: 'Ariel', 
    categoryName: 'Household Cleaning',
    barcode: '4084500168091',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Pampers Baby Dry Size 4', 
    nameAr: 'بامبرز بيبي دراي مقاس 4', 
    brandName: 'Pampers', 
    categoryName: 'Baby Food',
    barcode: '4015400507499',
    verdictLabel: 'AVOID' as const,
    description: 'Baby product - consider alternatives carefully',
    descriptionAr: 'منتج أطفال - ابحث عن بدائل بعناية',
  },
  { 
    nameEn: 'Gillette Fusion Razor', 
    nameAr: 'جيليت فيوجن شفرة', 
    brandName: 'Gillette', 
    categoryName: 'Personal Care',
    barcode: '7702018874477',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Head & Shoulders Shampoo 400ml', 
    nameAr: 'هيد آند شولدرز شامبو 400مل', 
    brandName: 'Head & Shoulders', 
    categoryName: 'Personal Care',
    barcode: '4084500205024',
    verdictLabel: 'AVOID' as const,
  },

  // Mondelez products
  { 
    nameEn: 'Oreo Original', 
    nameAr: 'أوريو أصلي', 
    brandName: 'Oreo', 
    categoryName: 'Snacks & Sweets',
    barcode: '7622210100535',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Cadbury Dairy Milk', 
    nameAr: 'كادبوري ديري ميلك', 
    brandName: 'Cadbury', 
    categoryName: 'Snacks & Sweets',
    barcode: '7622210601698',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Toblerone 100g', 
    nameAr: 'توبليرون 100غ', 
    brandName: 'Toblerone', 
    categoryName: 'Snacks & Sweets',
    barcode: '7614500010013',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Tang Orange 500g', 
    nameAr: 'تانج برتقال 500غ', 
    brandName: 'Tang', 
    categoryName: 'Juices',
    barcode: '7622300279493',
    verdictLabel: 'AVOID' as const,
  },

  // L'Oréal products
  { 
    nameEn: "L'Oréal Paris Excellence Hair Color", 
    nameAr: 'لوريال باريس إكسلنس صبغة شعر', 
    brandName: "L'Oréal Paris", 
    categoryName: 'Personal Care',
    barcode: '3600523781713',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Maybelline Mascara', 
    nameAr: 'مايبيلين ماسكارا', 
    brandName: 'Maybelline', 
    categoryName: 'Cosmetics',
    barcode: '3600530714469',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Garnier Fructis Shampoo', 
    nameAr: 'غارنييه فروكتيس شامبو', 
    brandName: 'Garnier', 
    categoryName: 'Personal Care',
    barcode: '3600541251434',
    verdictLabel: 'AVOID' as const,
  },

  // J&J products
  { 
    nameEn: "Johnson's Baby Shampoo 500ml", 
    nameAr: 'جونسون بيبي شامبو 500مل', 
    brandName: "Johnson's Baby", 
    categoryName: 'Baby Food',
    barcode: '3574661072883',
    verdictLabel: 'AVOID' as const,
    description: 'Baby product - consider alternatives carefully',
    descriptionAr: 'منتج أطفال - ابحث عن بدائل بعناية',
  },
  { 
    nameEn: 'Neutrogena Face Wash', 
    nameAr: 'نيوتروجينا غسول وجه', 
    brandName: 'Neutrogena', 
    categoryName: 'Personal Care',
    barcode: '3574661072852',
    verdictLabel: 'AVOID' as const,
  },
  { 
    nameEn: 'Listerine Mouthwash 500ml', 
    nameAr: 'ليسترين غسول فم 500مل', 
    brandName: 'Listerine', 
    categoryName: 'Personal Care',
    barcode: '3574661072845',
    verdictLabel: 'AVOID' as const,
  },

  // ===== ALTERNATIVES (PREFERRED) =====
  { 
    nameEn: 'RC Cola 330ml', 
    nameAr: 'آر سي كولا 330مل', 
    brandName: 'RC Cola', 
    categoryName: 'Soft Drinks',
    barcode: '070452200112',
    verdictLabel: 'PREFERRED' as const,
    description: 'Alternative to Coca-Cola and Pepsi',
    descriptionAr: 'بديل لكوكا كولا وبيبسي',
  },
  { 
    nameEn: 'Libyan Soda Orange 330ml', 
    nameAr: 'صودا ليبية برتقال 330مل', 
    brandName: 'Libyan Soda', 
    categoryName: 'Soft Drinks',
    barcode: '6281000000001',
    verdictLabel: 'PREFERRED' as const,
    description: 'Local Libyan alternative',
    descriptionAr: 'بديل محلي ليبي',
  },
  { 
    nameEn: 'Ülker Chocolate Wafer', 
    nameAr: 'أولكر ويفر شوكولاتة', 
    brandName: 'Ülker', 
    categoryName: 'Snacks & Sweets',
    barcode: '8690504030119',
    verdictLabel: 'PREFERRED' as const,
    description: 'Turkish alternative to KitKat',
    descriptionAr: 'بديل تركي لكيت كات',
  },
  { 
    nameEn: 'Eti Browni', 
    nameAr: 'إيتي براوني', 
    brandName: 'Eti', 
    categoryName: 'Snacks & Sweets',
    barcode: '8690526069098',
    verdictLabel: 'PREFERRED' as const,
    description: 'Turkish alternative snack',
    descriptionAr: 'سناك تركي بديل',
  },
];

