export const stores = [
  // Tripoli stores
  {
    name: 'Al-Mahary Supermarket',
    nameAr: 'سوبرماركت المهاري',
    city: 'Tripoli',
    area: 'Ben Ashour',
    address: 'Ben Ashour Main Street',
    addressAr: 'شارع بن عاشور الرئيسي',
    latitude: 32.8872,
    longitude: 13.1913,
    tags: ['supermarket', 'grocery'],
    isVerified: true,
  },
  {
    name: 'City Mall Supermarket',
    nameAr: 'سوبرماركت سيتي مول',
    city: 'Tripoli',
    area: 'Hay Al-Andalus',
    address: 'City Mall, Hay Al-Andalus',
    addressAr: 'سيتي مول، حي الأندلس',
    latitude: 32.8654,
    longitude: 13.0521,
    tags: ['supermarket', 'mall'],
    isVerified: true,
  },
  {
    name: 'Al-Nasr Market',
    nameAr: 'سوق النصر',
    city: 'Tripoli',
    area: 'Souq Al-Juma',
    address: 'Souq Al-Juma District',
    addressAr: 'منطقة سوق الجمعة',
    latitude: 32.8932,
    longitude: 13.1654,
    tags: ['market', 'grocery'],
    isVerified: true,
  },
  {
    name: 'Tripoli Central Pharmacy',
    nameAr: 'صيدلية طرابلس المركزية',
    city: 'Tripoli',
    area: 'Algeria Square',
    address: 'Near Algeria Square',
    addressAr: 'قرب ميدان الجزائر',
    latitude: 32.8925,
    longitude: 13.1870,
    tags: ['pharmacy'],
    isVerified: true,
  },

  // Benghazi stores
  {
    name: 'Benghazi Mall',
    nameAr: 'بنغازي مول',
    city: 'Benghazi',
    area: 'Benina Road',
    address: 'Benina Road',
    addressAr: 'طريق بنينا',
    latitude: 32.1167,
    longitude: 20.0667,
    tags: ['mall', 'supermarket'],
    isVerified: true,
  },
  {
    name: 'Al-Salam Supermarket',
    nameAr: 'سوبرماركت السلام',
    city: 'Benghazi',
    area: 'Downtown',
    address: 'Omar Al-Mukhtar Street',
    addressAr: 'شارع عمر المختار',
    latitude: 32.1145,
    longitude: 20.0689,
    tags: ['supermarket', 'grocery'],
    isVerified: true,
  },
  {
    name: 'Libya Pharmacy Benghazi',
    nameAr: 'صيدلية ليبيا بنغازي',
    city: 'Benghazi',
    area: 'Al-Fuwayhat',
    address: 'Al-Fuwayhat District',
    addressAr: 'منطقة الفويهات',
    latitude: 32.1098,
    longitude: 20.0754,
    tags: ['pharmacy'],
    isVerified: true,
  },

  // Misrata stores
  {
    name: 'Misrata Central Market',
    nameAr: 'سوق مصراتة المركزي',
    city: 'Misrata',
    area: 'City Center',
    address: 'Tripoli Street',
    addressAr: 'شارع طرابلس',
    latitude: 32.3754,
    longitude: 15.0925,
    tags: ['market', 'supermarket'],
    isVerified: true,
  },
  {
    name: 'Al-Hikma Pharmacy',
    nameAr: 'صيدلية الحكمة',
    city: 'Misrata',
    area: 'City Center',
    address: 'Central Misrata',
    addressAr: 'وسط مصراتة',
    latitude: 32.3765,
    longitude: 15.0912,
    tags: ['pharmacy'],
    isVerified: true,
  },

  // Sabha stores
  {
    name: 'Sabha Main Market',
    nameAr: 'سوق سبها الرئيسي',
    city: 'Sabha',
    area: 'City Center',
    address: 'Main Street',
    addressAr: 'الشارع الرئيسي',
    latitude: 27.0377,
    longitude: 14.4283,
    tags: ['market', 'grocery'],
    isVerified: true,
  },

  // Zawiya stores
  {
    name: 'Zawiya Supermarket',
    nameAr: 'سوبرماركت الزاوية',
    city: 'Zawiya',
    area: 'City Center',
    address: 'Main Road',
    addressAr: 'الطريق الرئيسي',
    latitude: 32.7571,
    longitude: 12.7278,
    tags: ['supermarket', 'grocery'],
    isVerified: true,
  },

  // Zliten stores
  {
    name: 'Zliten Market',
    nameAr: 'سوق زليتن',
    city: 'Zliten',
    area: 'City Center',
    address: 'Central Zliten',
    addressAr: 'وسط زليتن',
    latitude: 32.4674,
    longitude: 14.5687,
    tags: ['market', 'grocery'],
    isVerified: true,
  },
];

